### ISSUE TITLE
Show "Open chat" button on a bottom toolbar for small screens

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/lektor-icon#9]
The new rewrite of `lektor-icon` done by @CAM-Gerlach in PR #8 is fantastic! The only thing I'd like to see improved on small screens is to not display the "Open Chat" button directly because it takes too much space:

![Selección_086](https://user-images.githubusercontent.com/365293/92421779-e24aad80-f13f-11ea-81a4-4c1f3a2a35c5.png)

Instead, we could show it on a toolbar at the bottom, like we're doing in the docs website:

![imagen](https://user-images.githubusercontent.com/365293/92421849-39508280-f140-11ea-9c7c-2d6a6d64bc9e.png)

@CAM-Gerlach, could you take a look at this one? It's not critical, so whenever you have some free time is fine.

**Comment by CAM-Gerlach** [comment]
Yup, this would be a nice improvement. Since we don't have a bottom toolbar (as of yet) given we don't have the other things to put on it, I could just make the button smaller (less padding, basically) at moderately lower widths, and then turn into a small icon (as in the Pydata theme) at even smaller ones. Its not a priority for spyder-ide/lektor-icon#8 , but it shouldn't be too tough to do, either there if I get the time or in a followup PR.

**Comment by ccordoba12** [comment]
> I could just make the button smaller (less padding, basically) at moderately lower widths, and then turn into a small icon (as in the Pydata theme) at even smaller ones

Nice idea! I agree with it.

> Its not a priority for #8 , but it shouldn't be too tough to do, either there if I get the time or in a followup PR.

Up to you when you can implement it then.

**Comment by CAM-Gerlach** [comment]
As Gitter has now [dropped support for embedded chat with no immediate replacement](https://blog.gitter.im/2023/02/13/gitter-has-fully-migrated-to-matrix/) due to its switch to Matrix, this option is now considered deprecated, and will be removed in the next version of the theme. Therefore, there's no purpose in fixing this now, and this can be closed as wonfix.
